name: Build debug apk
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app-ultimate/build/outputs/apk/debug/app-ultimate-debug.apk

      - name: Upload to slack step
        uses: MeilCli/slack-upload-file@v1
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channels: random
          file_path: 'app-ultimate/build/outputs/apk/debug/'
          file_name: 'lapp-ultimate-debug.apk'
          file_type: 'apk'
          initial_comment: 'post by slack-upload-file'
